version: "3.8"
services:
  cypress:
    build:
      context: .
    volumes:
      - .:/app
    working_dir: /app
    ports:
      - "8080:8080" # Cambia según lo necesites
    environment:
      - CYPRESS_baseUrl=http://localhost:3000 # Cambia la URL base si es necesario
    entrypoint: ["npx", "cypress", "run"]
